/**
 * Canonical audit_logs.action values. Strings persisted in the database, so
 * never rename without a migration — downstream dashboards / queries (the
 * CMS audit trail view in particular) match on these literals.
 *
 * Add new actions here so a single grep tells you the full vocabulary the
 * API ever writes to `audit_logs.action`.
 */
export const AUDIT_ACTIONS = {
  USER_LOGIN: 'USER_LOGIN',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_PASSWORD_RESET_BY_ADMIN: 'USER_PASSWORD_RESET_BY_ADMIN',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',

  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_DELETED: 'ROLE_DELETED',
  ROLE_ASSIGNED_TO_USER: 'ROLE_ASSIGNED_TO_USER',
  ROLE_REMOVED_FROM_USER: 'ROLE_REMOVED_FROM_USER',
  PERMISSION_ASSIGNED_TO_ROLE: 'PERMISSION_ASSIGNED_TO_ROLE',
  PERMISSION_REMOVED_FROM_ROLE: 'PERMISSION_REMOVED_FROM_ROLE',

  POST_CREATED: 'POST_CREATED',
  POST_UPDATED: 'POST_UPDATED',
  POST_DELETED: 'POST_DELETED',
  POST_RESTORED: 'POST_RESTORED',
  POST_PUBLISHED: 'POST_PUBLISHED',
  POST_UNPUBLISHED: 'POST_UNPUBLISHED',

  POST_CATEGORY_CREATED: 'POST_CATEGORY_CREATED',
  POST_CATEGORY_UPDATED: 'POST_CATEGORY_UPDATED',
  POST_CATEGORY_DELETED: 'POST_CATEGORY_DELETED',
  POST_CATEGORY_RESTORED: 'POST_CATEGORY_RESTORED',

  BOOK_CREATED: 'BOOK_CREATED',
  BOOK_UPDATED: 'BOOK_UPDATED',
  BOOK_DELETED: 'BOOK_DELETED',
  BOOK_RESTORED: 'BOOK_RESTORED',

  BOOK_CATEGORY_CREATED: 'BOOK_CATEGORY_CREATED',
  BOOK_CATEGORY_UPDATED: 'BOOK_CATEGORY_UPDATED',
  BOOK_CATEGORY_DELETED: 'BOOK_CATEGORY_DELETED',
  BOOK_CATEGORY_RESTORED: 'BOOK_CATEGORY_RESTORED',

  ACADEMIC_PAPER_CREATED: 'ACADEMIC_PAPER_CREATED',
  ACADEMIC_PAPER_UPDATED: 'ACADEMIC_PAPER_UPDATED',
  ACADEMIC_PAPER_DELETED: 'ACADEMIC_PAPER_DELETED',
  ACADEMIC_PAPER_RESTORED: 'ACADEMIC_PAPER_RESTORED',

  ACADEMIC_PAPER_CATEGORY_CREATED: 'ACADEMIC_PAPER_CATEGORY_CREATED',
  ACADEMIC_PAPER_CATEGORY_UPDATED: 'ACADEMIC_PAPER_CATEGORY_UPDATED',
  ACADEMIC_PAPER_CATEGORY_DELETED: 'ACADEMIC_PAPER_CATEGORY_DELETED',
  ACADEMIC_PAPER_CATEGORY_RESTORED: 'ACADEMIC_PAPER_CATEGORY_RESTORED',

  GALLERY_IMAGE_CREATED: 'GALLERY_IMAGE_CREATED',
  GALLERY_IMAGE_UPDATED: 'GALLERY_IMAGE_UPDATED',
  GALLERY_IMAGE_DELETED: 'GALLERY_IMAGE_DELETED',
  GALLERY_IMAGE_RESTORED: 'GALLERY_IMAGE_RESTORED',

  GALLERY_CATEGORY_CREATED: 'GALLERY_CATEGORY_CREATED',
  GALLERY_CATEGORY_UPDATED: 'GALLERY_CATEGORY_UPDATED',
  GALLERY_CATEGORY_DELETED: 'GALLERY_CATEGORY_DELETED',
  GALLERY_CATEGORY_RESTORED: 'GALLERY_CATEGORY_RESTORED',

  MEDIA_CREATED: 'MEDIA_CREATED',
  MEDIA_UPDATED: 'MEDIA_UPDATED',
  MEDIA_DELETED: 'MEDIA_DELETED',
  MEDIA_VARIANTS_REGENERATED: 'MEDIA_VARIANTS_REGENERATED',

  DAILY_HADITH_CREATED: 'DAILY_HADITH_CREATED',
  DAILY_HADITH_UPDATED: 'DAILY_HADITH_UPDATED',
  DAILY_HADITH_DELETED: 'DAILY_HADITH_DELETED',
  DAILY_HADITH_PINNED: 'DAILY_HADITH_PINNED',
  DAILY_HADITH_UNPINNED: 'DAILY_HADITH_UNPINNED',

  CONTACT_SUBMITTED: 'CONTACT_SUBMITTED',
  CONTACT_UPDATED: 'CONTACT_UPDATED',
  CONTACT_DELETED: 'CONTACT_DELETED',
  PROXY_VISIT_SUBMITTED: 'PROXY_VISIT_SUBMITTED',
  PROXY_VISIT_UPDATED: 'PROXY_VISIT_UPDATED',
  PROXY_VISIT_DELETED: 'PROXY_VISIT_DELETED',

  NEWSLETTER_SUBSCRIBED: 'NEWSLETTER_SUBSCRIBED',
  NEWSLETTER_UNSUBSCRIBED: 'NEWSLETTER_UNSUBSCRIBED',
  NEWSLETTER_RESUBSCRIBED: 'NEWSLETTER_RESUBSCRIBED',
  NEWSLETTER_UNSUBSCRIBED_BY_ADMIN: 'NEWSLETTER_UNSUBSCRIBED_BY_ADMIN',
  NEWSLETTER_RESUBSCRIBED_BY_ADMIN: 'NEWSLETTER_RESUBSCRIBED_BY_ADMIN',
  NEWSLETTER_SUBSCRIBER_DELETED: 'NEWSLETTER_SUBSCRIBER_DELETED',

  NEWSLETTER_CAMPAIGN_CREATED: 'NEWSLETTER_CAMPAIGN_CREATED',
  NEWSLETTER_CAMPAIGN_UPDATED: 'NEWSLETTER_CAMPAIGN_UPDATED',
  NEWSLETTER_CAMPAIGN_DELETED: 'NEWSLETTER_CAMPAIGN_DELETED',
  NEWSLETTER_CAMPAIGN_CANCELLED: 'NEWSLETTER_CAMPAIGN_CANCELLED',
  NEWSLETTER_CAMPAIGN_SEND_QUEUED: 'NEWSLETTER_CAMPAIGN_SEND_QUEUED',
  NEWSLETTER_CAMPAIGN_COMPLETED: 'NEWSLETTER_CAMPAIGN_COMPLETED',

  SETTING_CREATED: 'SETTING_CREATED',
  SETTING_UPDATED: 'SETTING_UPDATED',
  SETTING_DELETED: 'SETTING_DELETED',

  LANGUAGE_CREATED: 'LANGUAGE_CREATED',
  LANGUAGE_UPDATED: 'LANGUAGE_UPDATED',
  LANGUAGE_DELETED: 'LANGUAGE_DELETED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
