/**
 * Response comparison for the diff harness. Pure: no I/O, unit-tested in compare.test.ts.
 *
 * Compared: status, content-type, etag and the body. Ignored: the envelope's `timestamp` and the error
 * envelope's `requestId` (a per-process counter on Nest, the cf-ray or a uuid on the Worker). Normalized:
 * - ids: UUIDs that differ are equal if they pair consistently (A's id X is always B's id Y). New
 *   pairs are accepted only in write scenarios; on reads from identical copies any id mismatch is a diff.
 * - dates: ISO datetimes that differ are equal when both were generated during this run.
 */

export interface Captured {
  status: number;
  contentType: string;
  etag: string | null;
  body: string;
}

export interface Diff {
  field: string;
  a: string;
  b: string;
}

export interface CompareContext {
  ids: IdMap;
  /** Epoch ms when the run started; datetimes at or after it (minus clock skew) were generated by the run. */
  runStart: number;
  /** Write scenarios create rows, so new id pairs are expected; reads never create them. */
  allowNewIds: boolean;
}

/** A bijection between ids generated on A and on B. */
export class IdMap {
  private ab = new Map<string, string>();
  private ba = new Map<string, string>();

  pair(a: string, b: string, allowNew: boolean): boolean {
    const knownB = this.ab.get(a);
    const knownA = this.ba.get(b);
    if (knownB !== undefined || knownA !== undefined) return knownB === b && knownA === a;
    if (!allowNew) return false;
    this.ab.set(a, b);
    this.ba.set(b, a);
    return true;
  }

  /** B's id for A's id, if paired (scenarios use it to fill paths). */
  toB(a: string): string | undefined {
    return this.ab.get(a);
  }
}

const CLOCK_SKEW_MS = 2000;
const MAX_DIFFS = 25;
const TOKEN = /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2}))/i;
const UUID = /^[0-9a-f]{8}-/i;

const show = (v: unknown) => {
  const s = v === undefined ? '<missing>' : typeof v === 'string' ? JSON.stringify(v) : JSON.stringify(v) ?? String(v);
  return s.length > 120 ? `${s.slice(0, 117)}...` : s;
};

class Walker {
  diffs: Diff[] = [];
  /** True once a generated id or date made two different values equal: their bytes (and ETags) differ legitimately. */
  normalized = false;

  constructor(private ctx: CompareContext) {}

  add(field: string, a: unknown, b: unknown) {
    if (this.diffs.length < MAX_DIFFS) this.diffs.push({ field, a: show(a), b: show(b) });
    else if (this.diffs.length === MAX_DIFFS) this.diffs.push({ field: '...', a: 'more diffs not shown', b: '' });
  }

  /** Equal strings, or equal once ids and run-generated dates inside them are matched up. */
  sameString(a: string, b: string): boolean {
    if (a === b) return true;
    const pa = a.split(TOKEN);
    const pb = b.split(TOKEN);
    if (pa.length !== pb.length) return false;
    const since = this.ctx.runStart - CLOCK_SKEW_MS;
    const idPairs: [string, string][] = [];
    for (let i = 0; i < pa.length; i++) {
      if (pa[i] === pb[i]) continue;
      if (i % 2 === 0) return false; // literal text between tokens
      if (UUID.test(pa[i]) !== UUID.test(pb[i])) return false;
      if (UUID.test(pa[i])) idPairs.push([pa[i].toLowerCase(), pb[i].toLowerCase()]);
      else if (!(Date.parse(pa[i]) >= since && Date.parse(pb[i]) >= since)) return false;
    }
    // Pair ids only once the rest matched, so a mismatch elsewhere records no pairing.
    if (!idPairs.every(([x, y]) => this.ctx.ids.pair(x, y, this.ctx.allowNewIds))) return false;
    this.normalized = true;
    return true;
  }

  walk(a: unknown, b: unknown, at: string) {
    if (typeof a === 'string' && typeof b === 'string') {
      if (!this.sameString(a, b)) this.add(at, a, b);
      return;
    }
    if (Array.isArray(a) && Array.isArray(b)) {
      if (a.length !== b.length) this.add(`${at}.length`, a.length, b.length);
      for (let i = 0; i < Math.min(a.length, b.length); i++) this.walk(a[i], b[i], `${at}[${i}]`);
      return;
    }
    if (isObject(a) && isObject(b)) {
      const ka = Object.keys(a);
      const kb = Object.keys(b);
      for (const k of ka) this.walk(a[k], b[k], `${at}.${k}`);
      for (const k of kb) if (!(k in a)) this.add(`${at}.${k}`, undefined, b[k]);
      const shared = ka.filter((k) => k in b);
      if (shared.join() !== kb.filter((k) => k in a).join()) this.add(`${at} (key order)`, shared, kb.filter((k) => k in a));
      return;
    }
    if (a !== b) this.add(at, a, b);
  }
}

const isObject = (v: unknown): v is Record<string, unknown> => typeof v === 'object' && v !== null && !Array.isArray(v);

/** `perRequest`: an error envelope. Its requestId and mid-body timestamp make every ETag unique, so ETags aren't compared. */
function parseJson(r: Captured): { ok: true; value: unknown; perRequest: boolean } | { ok: false } {
  if (!/json/.test(r.contentType)) return { ok: false };
  try {
    const value = JSON.parse(r.body);
    const perRequest = isObject(value) && 'requestId' in value;
    if (isObject(value)) {
      delete value.timestamp;
      delete value.requestId;
    }
    return { ok: true, value, perRequest };
  } catch {
    return { ok: false };
  }
}

export function compare(a: Captured, b: Captured, ctx: CompareContext): Diff[] {
  const w = new Walker(ctx);
  if (a.status !== b.status) w.add('status', a.status, b.status);
  if (a.contentType !== b.contentType) w.add('content-type', a.contentType, b.contentType);

  const ja = parseJson(a);
  const jb = parseJson(b);
  if (ja.ok && jb.ok) {
    w.walk(ja.value, jb.value, '$');
    if (ja.perRequest || jb.perRequest) w.normalized = true;
  }
  else if (!w.sameString(a.body, b.body)) {
    const la = a.body.split('\n');
    const lb = b.body.split('\n');
    const line = la.findIndex((l, i) => !w.sameString(l, lb[i] ?? ''));
    const at = line === -1 ? la.length : line;
    w.add(`body line ${at + 1}`, la[at], lb[at]);
  }

  // Identical content must hash to the identical ETag (envelopeEtag). Normalized content differs in bytes.
  if (w.diffs.length === 0 && !w.normalized && a.etag !== b.etag) w.add('etag', a.etag, b.etag);
  return w.diffs;
}
