import type { PrismaClient } from '../generated/prisma/client';

/** `Env` is generated by `wrangler types`; secrets and optional vars are not in wrangler.jsonc. */
export type AppBindings = Env & {
  JWT_SECRET: string;
  ENFORCE_PASSWORD_CHANGE_AFTER_RESET?: string;
  BCRYPT_ROUNDS?: string;
  JWT_EXPIRES_IN?: string;
  REFRESH_REUSE_GRACE_SECONDS?: string;
  TWILIO_ACCOUNT_SID?: string;
  TWILIO_AUTH_TOKEN?: string;
  TWILIO_WHATSAPP_FROM?: string;
  TWILIO_TEMPLATE_SID?: string;
  CONTEST_ATTEMPT_SECRET?: string;
  CONTEST_REVEAL_SCORE?: string;
  R2_ACCOUNT_ID?: string;
  R2_ACCESS_KEY_ID?: string;
  R2_SECRET_ACCESS_KEY?: string;
  R2_BUCKET?: string;
  R2_UPLOAD_URL_TTL_SECONDS?: string;
  SITE_TIMEZONE?: string;
  PUBLIC_SITE_URL?: string;
  PUBLIC_SITE_NAME?: string;
  YOUTUBE_CHANNEL_ID?: string;
};

export interface CurrentUser {
  id: string;
  username: string;
  permissions: string[];
}

export type AppEnv = {
  Bindings: AppBindings;
  Variables: {
    db: PrismaClient;
    user: CurrentUser;
    /** Two-letter language from Accept-Language, or null (Nest's `req.lang`). */
    lang: string | null;
    /** Client IP from CF-Connecting-IP (Nest's `req.ip`). */
    ip: string;
    /** Background work started with `defer`; closeDb waits for it before closing the pool. */
    deferred: Promise<unknown>[];
  };
};
