import type { PrismaClient } from '../generated/prisma/client';

/** `Env` is generated by `wrangler types`; secrets and optional vars are not in wrangler.jsonc. */
export type AppBindings = Env & {
  JWT_SECRET: string;
  ENFORCE_PASSWORD_CHANGE_AFTER_RESET?: string;
  SITE_TIMEZONE?: string;
};

export interface CurrentUser {
  id: string;
  username: string;
  permissions: string[];
}

export type AppEnv = {
  Bindings: AppBindings;
  Variables: {
    db: PrismaClient;
    user: CurrentUser;
    /** Two-letter language from Accept-Language, or null (Nest's `req.lang`). */
    lang: string | null;
    /** Client IP from CF-Connecting-IP (Nest's `req.ip`). */
    ip: string;
    /** Background work started with `defer`; closeDb waits for it before closing the pool. */
    deferred: Promise<unknown>[];
  };
};
