import type { Scenario } from '../scenario';

const BASE = '/api/v1/posts';
const CATEGORIES = '/api/v1/post-categories';
const MISSING = '00000000-0000-4000-8000-000000000000';
const ar = (title: string, extra: Record<string, unknown> = {}) => ({ lang: 'ar', title, body: `<p>${title}</p>`, is_default: true, ...extra });
const en = (title: string, extra: Record<string, unknown> = {}) => ({ lang: 'en', title, body: `<p>${title}</p>`, ...extra });
const category = (slug: string) => ({ translations: [{ lang: 'ar', title: slug, slug }] });

export default [
  {
    name: 'lifecycle',
    steps: [
      { method: 'POST', path: CATEGORIES, body: category('diff-posts-a'), capture: { cat_a: 'data.id' } },
      { method: 'POST', path: CATEGORIES, body: category('diff-posts-b'), capture: { cat_b: 'data.id' } },
      // Media is not ported yet, so the scenario borrows one from an existing book.
      { method: 'GET', path: '/api/v1/books/admin?limit=1', capture: { media: 'data.items.0.cover_image_id' } },
      {
        method: 'POST',
        path: BASE,
        body: {
          category_id: '{{cat_a}}',
          cover_image_id: '{{media}}',
          slug: 'diff-posts-one',
          is_featured: true,
          attachment_ids: ['{{media}}'],
          translations: [ar('Diff ar', { summary: 'S', meta_title: 'MT', meta_description: 'MD', body: '<p onclick="x()">Diff</p><script>1</script>' }), en('Diff en')],
        },
        capture: { a: 'data.id' },
      },
      { method: 'POST', path: BASE, body: { category_id: '{{cat_a}}', slug: 'diff-posts-two', is_published: true, published_at: '2020-01-02T03:04:05Z', translations: [ar('Two')] }, capture: { b: 'data.id' } },
      { method: 'POST', path: BASE, body: { category_id: '{{cat_a}}', slug: 'diff-posts-future', published_at: '2099-01-01T00:00:00Z', translations: [ar('Future')] }, capture: { c: 'data.id' } },
      { method: 'POST', path: BASE, body: { category_id: '{{cat_a}}', slug: 'diff-posts-clamped', is_published: true, published_at: '2099-01-01T00:00:00Z', translations: [ar('Clamped')] }, capture: { d: 'data.id' } },
      { method: 'POST', path: BASE, body: { category_id: MISSING, slug: 'diff-posts-x', translations: [ar('No category')] } },
      { method: 'POST', path: BASE, body: { category_id: '{{cat_a}}', slug: 'diff-posts-x', cover_image_id: MISSING, translations: [ar('No cover')] } },
      { method: 'POST', path: BASE, body: { category_id: '{{cat_a}}', slug: 'diff-posts-x', translations: [ar('No og', { og_image_id: MISSING })] } },
      { method: 'POST', path: BASE, body: { category_id: '{{cat_a}}', slug: 'diff-posts-x', translations: [en('No default')] } },
      { method: 'POST', path: BASE, body: { category_id: '{{cat_a}}', slug: 'diff-posts-one', translations: [ar('Dup slug')] } },
      { method: 'POST', path: BASE, body: { category_id: '{{cat_a}}', slug: 'diff-posts-x', translations: [ar('Dup lang'), ar('Dup lang 2', { is_default: false })] } },
      { method: 'POST', path: BASE, body: { category_id: '{{cat_a}}', slug: 'diff-posts-x', attachment_ids: ['{{media}}', '{{media}}'], translations: [ar('Dup attachment')] } },
      { method: 'POST', path: BASE, body: { category_id: 'nope', slug: 'Bad Slug', published_at: '2026-06-01T09:00:00', translations: [] } },
      { method: 'GET', path: `${BASE}/{{a}}`, auth: 'anon' },
      { method: 'GET', path: `${BASE}/{{a}}`, auth: 'anon', lang: 'en' },
      { method: 'GET', path: `${BASE}/{{b}}`, auth: 'anon' },
      { method: 'GET', path: `${BASE}/{{c}}`, auth: 'anon' },
      { method: 'GET', path: `${BASE}/admin/{{a}}`, lang: 'en' },
      { method: 'GET', path: `${BASE}/admin/{{d}}` },
      { method: 'GET', path: `${BASE}/by-slug/diff-posts-two`, auth: 'anon' },
      { method: 'GET', path: `${BASE}/by-slug/diff-posts-future`, auth: 'anon' },
      { method: 'GET', path: `${BASE}?category_id={{cat_a}}`, auth: 'anon' },
      { method: 'GET', path: `${BASE}?category_id={{cat_a}}&featured=true&sort=views`, auth: 'anon', lang: 'en' },
      { method: 'GET', path: `${BASE}?category_id={{cat_a}}&search=Diff`, auth: 'anon' },
      { method: 'GET', path: `${BASE}/admin?category_id={{cat_a}}&status=scheduled` },
      { method: 'GET', path: `${BASE}/admin?category_id={{cat_a}}&status=draft` },
      { method: 'GET', path: `${BASE}/admin?category_id={{cat_a}}&status=published` },
      { method: 'POST', path: `${BASE}/{{b}}/view`, auth: 'anon' },
      { method: 'POST', path: `${BASE}/{{c}}/view`, auth: 'anon' },
      { method: 'PATCH', path: `${BASE}/{{a}}`, body: { category_id: '{{cat_b}}', is_featured: false, attachment_ids: [], translations: [en('Diff en 2', { summary: 'S2' }), ar('Diff ar 2')] } },
      { method: 'PATCH', path: `${BASE}/{{a}}`, body: { slug: 'diff-posts-renamed', published_at: '2099-02-02T00:00:00+03:00' } },
      { method: 'PATCH', path: `${BASE}/{{a}}`, body: { translations: [en('Second default', { is_default: true })] } },
      { method: 'PATCH', path: `${BASE}/{{a}}`, body: { category_id: MISSING } },
      { method: 'PATCH', path: `${BASE}/{{a}}`, body: { cover_image_id: MISSING } },
      { method: 'PATCH', path: `${BASE}/{{a}}`, body: { slug: 'diff-posts-two' } },
      { method: 'PATCH', path: `${BASE}/{{a}}`, body: { cover_image_id: null, published_at: null } },
      { method: 'PATCH', path: `${BASE}/{{b}}`, body: { slug: 'diff-posts-locked' } },
      { method: 'PATCH', path: `${BASE}/{{b}}`, body: { slug: 'diff-posts-unlocked', is_published: false, published_at: '2020-01-02T03:04:05Z' } },
      { method: 'PATCH', path: `${BASE}/{{a}}/publish`, body: { is_published: true } },
      { method: 'PATCH', path: `${BASE}/{{a}}/publish`, body: { is_published: true } },
      { method: 'PATCH', path: `${BASE}/{{a}}/publish`, body: { is_published: 'yes' } },
      { method: 'PATCH', path: `${BASE}/{{c}}/publish`, body: { is_published: true } },
      { method: 'PATCH', path: `${BASE}/{{c}}/publish`, body: { is_published: false } },
      { method: 'POST', path: `${BASE}/bulk/publish`, body: { ids: ['{{a}}', '{{b}}', '{{c}}', MISSING], is_published: true } },
      { method: 'POST', path: `${BASE}/bulk/publish`, body: { ids: ['{{a}}', '{{b}}'], is_published: false } },
      { method: 'POST', path: `${BASE}/bulk/publish`, body: { ids: ['{{a}}', '{{a}}'], is_published: true } },
      { method: 'POST', path: `${BASE}/bulk/publish`, body: { ids: [], is_published: true } },
      { method: 'POST', path: `${BASE}/bulk/delete`, body: { ids: ['{{c}}', MISSING] } },
      { method: 'POST', path: `${BASE}/bulk/delete`, body: { ids: ['{{c}}'] } },
      { method: 'DELETE', path: `${BASE}/{{d}}` },
      { method: 'DELETE', path: `${BASE}/{{a}}` },
      { method: 'DELETE', path: `${BASE}/{{a}}` },
      { method: 'GET', path: `${BASE}/trash?limit=100` },
      { method: 'POST', path: `${BASE}/{{c}}/restore` },
      { method: 'POST', path: `${BASE}/{{a}}/restore` },
      { method: 'POST', path: `${BASE}/{{a}}/restore` },
      { method: 'POST', path: BASE, body: { category_id: '{{cat_a}}', slug: 'diff-posts-two', translations: [ar('Takes slug')] } },
      { method: 'DELETE', path: `${BASE}/{{b}}` },
      { method: 'DELETE', path: `${BASE}/{{a}}` },
      { method: 'DELETE', path: `${CATEGORIES}/{{cat_b}}` },
      { method: 'POST', path: `${BASE}/{{a}}/restore` },
      { method: 'GET', path: `${BASE}/{{a}}`, auth: 'anon' },
    ],
  },
] satisfies Scenario[];
